- name: Run Monitor
        run: python main.py
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      - name: Deploy Data and Map
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data.json index.html
          git commit -m "Update hydrological data" || exit 0
          git push
